#!/bin/sh

ISSMALLBIN=""
ISSIMPLE=""

main() {
rm a.out 2>/dev/null
compile -c vm.c && \
{
  if [ -n "$ISSMALLBIN" ]; then
    strip \
    -S \
    --strip-unneeded \
    --remove-section=.note.gnu.gold-version \
    --remove-section=.comment \
    --remove-section=.note \
    --remove-section=.note.gnu.build-id \
    --remove-section=.note.ABI-tag \
    vm.o
    # -s
  else
    true
  fi &&
  compile -flto vm.o test-vm.c
} && {

valgrind \
  --leak-check=full \
  --show-leak-kinds=all \
  --num-callers=20 \
  --malloc-fill=0xaa \
  --free-fill=0x55 \
  --redzone-size=256 \
  --read-var-info=yes \
  --expensive-definedness-checks=yes \
  --merge-recursive-frames=10 \
  --track-origins=yes \
  --partial-loads-ok=no \
  ./a.out "$@"
}

local S=$?
echo $S
return $S
#-fsanitize=address -fsanitize=leak -fsanitize=undefined
}

compile() {
local ADD=""
if [ -n "$ISSMALLBIN" ]; then
: \
  -fshort-double \
  -ffunction-sections \
  -fdata-sections \
  -fno-jump-tables \
#

  ADD="$ADD \
  -Os \
  -Wno-error=suggest-attribute=pure \
  -Wno-error=suggest-attribute=const \
  -fno-asynchronous-unwind-tables \
  -fno-unwind-tables \
  -fno-stack-protector \
  -fno-unroll-loops \
  -fno-ident \
  -mfpmath=387 \
  -mfancy-math-387 \
  -fsingle-precision-constant \
  -Wl,-z,norelro \
  -Wl,--build-id=none \
  -U_FORTIFY_SOURCE \
  -DSMALLBIN \
  -s\
  "
  ./gcc-warn.sh -D'__attribute__(_)=' $ADD "$@"
elif [ -n "$ISSIMPLE" ]; then
  ADD="$ADD -O2 -g -DSIMPLE"
  ./gcc-warn.sh $ADD "$@"
else
  ADD="$ADD -O2 -g"
  ./gcc-warn.sh $ADD "$@"
fi
}

main "$@"
