#!/bin/sh

# environment variables:
# * ISSMALLBIN: 1 = size optimization experiments
# * ISQUICK: 1 = skip valgrind and run tests natively
# * ISSIMPLE: 1 = reduce complexity, never deallocate memory

main() {
  rm a.out 2>/dev/null
  compile -c vm.c && \
  {
    if [ -n "$ISSMALLBIN" ]; then
      strip \
      -S \
      --strip-unneeded \
      --remove-section=.note.gnu.gold-version \
      --remove-section=.comment \
      --remove-section=.note \
      --remove-section=.note.gnu.build-id \
      --remove-section=.note.ABI-tag \
      vm.o
      # -s
    else
      true
    fi &&
    compile -flto vm.o test-vm.c testutil.c
  } && {

    if [ -n "$ISQUICK" ]; then
      ./a.out "$@"
    else
      valgrind \
        --leak-check=full \
        --show-leak-kinds=all \
        --num-callers=30 \
        --malloc-fill=0xaa \
        --free-fill=0x55 \
        --redzone-size=256 \
        --read-var-info=yes \
        --expensive-definedness-checks=yes \
        --merge-recursive-frames=10 \
        --track-origins=yes \
        --partial-loads-ok=no \
        ./a.out "$@"
        #-fsanitize=address -fsanitize=leak -fsanitize=undefined
    fi
  }

  local S=$?
  echo $S
  return $S
}

compile() {
  local ADD=""
  if [ -n "$ISSMALLBIN" ]; then
  : \
    -fshort-double \
    -ffunction-sections \
    -fdata-sections \
    -fno-jump-tables \
  #

    ADD="$ADD \
    -Os \
    -Wno-error=suggest-attribute=pure \
    -Wno-error=suggest-attribute=const \
    -Wno-error=unused-function \
    -fno-asynchronous-unwind-tables \
    -fno-unwind-tables \
    -fira-region=mixed \
    -fno-stack-protector \
    -fno-unroll-loops \
    -fno-ident \
    -mfpmath=387 \
    -mfancy-math-387 \
    -fsingle-precision-constant \
    -Wl,-z,norelro \
    -Wl,--build-id=none \
    -U_FORTIFY_SOURCE \
    -DSMALLBIN \
    -DNDEBUG \
    -s\
    "
    ./gcc-warn.sh $ADD "$@" # -D'__attribute__(_)=' (TODO useful for putsn())
  elif [ -n "$ISSIMPLE" ]; then
    ADD="$ADD -O2 -g -DSIMPLE"
    ./gcc-warn.sh $ADD "$@"
  else
    ADD="$ADD -Og -g"
    ./gcc-warn.sh $ADD "$@"
  fi
}

main "$@"
